### ISSUE TITLE
bootstrap/autoload.php issue

### ISSUE THREAD

**Issue by manojkumar1412** [shashank-srikant/sevasetu-mothercare#26]
There is a line of code on index.php which loads bootstrap/autoload.php and this file internally try to execute below statement.
require **DIR**.'/../vendor/autoload.php';

which doesn't exist in repo. Not sure whether this line needs to be commented or the file needs to be committed in repo or it was left intentionally.

Please let me know the fix for it so that i can also start contributing.

Thanks

**Comment by shashank-srikant** [comment]
There's a vendor folder which needs to be added separately.
Once that's added, the build works correctly. 
This is a larger problem to prepare a proper installable and is documented right. Will open it as a separate issue and chase.
